### PR TITLE
Dmichelotto patch 1

### LINKED ISSUE #12: Fails to get disk statistics on Ubuntu 18.04 due to changed iostat output format
iostat on Ubuntu 18.04 no longer prints "Device:" for the disk headers, but rather just "Device" (without the colon). This makes the regexp trying to find disks fail.

`iostat -x` output on Ubuntu 14.04:
```Linux 3.8.0-29-generic (mario1)         09/13/2018      _x86_64_        (16 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.87    0.00    0.10    0.39    0.00   98.64

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00    17.34    0.75   51.82    26.02   612.08    24.28     0.00    0.68    0.99    0.67   0.57   3.01
dm-0              0.00     0.00    0.75   58.95    26.01   612.07    21.38     0.00    0.04    0.99    0.03   0.51   3.02
dm-1              0.00     0.00    0.00    0.00     0.01     0.01     8.00     0.00    5.38    1.54    7.87   0.26   0.00
```

`iostat -x` output on Ubutun 18.04 (note the lack of colon after "Device"):
```Linux 4.15.0-32-generic (behemoth1)     09/13/2018      _x86_64_        (40 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.40    0.00    0.08    0.01    0.00   99.51

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
nvme0n1          9.56  647.89    158.28   5024.43     0.00    22.81   0.00   3.40    0.08    0.08   0.05    16.56     7.76   0.00   0.06
dm-0             9.46  663.13    158.22   5023.83     0.00     0.00   0.00   0.00    0.08    0.02   0.01    16.72     7.58   0.01   0.66
```

Not sure what exactly caused this (some update to the sysstat package?), just noticed it when the check didn't work on our 18.04 server.

### PR DESCRIPTION
**Pull request by dmichelotto**
## Pull Request Checklist

Fix #12 

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Fix wrong parsing for iostat output after package upgrade > 10

Before:
```bash
/opt/sensu/embedded/bin/metrics-iostat-extended.rb --scheme test
test.avg-cpu.pct_user 8.5 1540197146
test.avg-cpu.pct_nice 0.0 1540197146
test.avg-cpu.pct_system 2.25 1540197146
test.avg-cpu.pct_iowait 0.0 1540197146
test.avg-cpu.pct_steal 0.0 1540197146
test.avg-cpu.pct_idle 89.25 1540197146
```

After:
```bash
/opt/sensu/embedded/bin/metrics-iostat-extended.rb --scheme test
test.avg-cpu.pct_user 8.5 1540197146
test.avg-cpu.pct_nice 0.0 1540197146
test.avg-cpu.pct_system 2.25 1540197146
test.avg-cpu.pct_iowait 0.0 1540197146
test.avg-cpu.pct_steal 0.0 1540197146
test.avg-cpu.pct_idle 89.25 1540197146
test.sda.r_per_s 0.0 1540197146
test.sda.w_per_s 0.0 1540197146
test.sda.rkB_per_s 0.0 1540197146
test.sda.wkB_per_s 0.0 1540197146
test.sda.rrqm_per_s 0.0 1540197146
test.sda.wrqm_per_s 0.0 1540197146
test.sda.pct_rrqm 0.0 1540197146
test.sda.pct_wrqm 0.0 1540197146
test.sda.r_await 0.0 1540197146
test.sda.w_await 0.0 1540197146
test.sda.aqu-sz 0.0 1540197146
test.sda.rareq-sz 0.0 1540197146
test.sda.wareq-sz 0.0 1540197146
test.sda.svctm 0.0 1540197146
test.sda.pct_util 0.0 1540197146
```

### CODE REVIEW

**Comment by majormoses** [comment]
Thanks for your contribution to Sensu plugins! Without people like you submitting PRs we couldn't run the project. I will review it shortly.

**Comment by majormoses** [comment]
Looks good from a quick glance, regex might be a bit too forgiving, I need to look at the output when I have a minute. I am at the airport and they just announced boarding so I will get to merging/releasing this later. Can you please provide a manual or automated [testing artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts) for Ubuntu 14.04 and 18.04?

File: bin/metrics-iostat-extended.rb [hunk 1]
```diff
@@ -85,7 +85,7 @@ def parse_results(raw)
         headers = line.gsub(/%/, 'pct_').split(/\s+/)
         headers.shift
         next
-      when /^(Device):/
+      when /^(Device).*/
```
Comment (majormoses) [inline bin/metrics-iostat-extended.rb]: To be a bit more specific we could use `when /^(Device):\s+.+/, /^(Device)\s+.+/`

**Comment by dmichelotto** [comment]
Hi @majormoses ,

sorry for the missing parts, I read the documentation but I left something.

I have just updated the first comment with the testing artifact part. Let me know if something is missing again.

**Comment by dmichelotto** [comment]
Hi @majormoses ,

sorry for the missing parts, I read the documentation but I left something.

I have just updated the first comment with the testing artifact part. Let me know if something is missing again.

**Comment by dmichelotto** [comment]
Hi @majormoses ,

sorry for the missing parts, I read the documentation but I left something.

I have just updated the first comment with the testing artifact part. Let me know if something is missing again.

**Review by majormoses — APPROVED** [review]
Sorry I was traveling back home now, test looks good. LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-io-checks/versions/1.0.2
